USE DATABASE TRAVEL_DB;

USE SCHEMA RAW;


CREATE OR REPLACE TABLE CUSTOMER_BOOKINGS_DATA (
    CURRENCY_CODE VARCHAR,
    STATUS VARCHAR,
    PHONE_NUMBER VARCHAR,
    BOOKING_DATE VARCHAR,
    SEGMENT_ID NUMBER,
    FIRST_NAME VARCHAR,
    BOOKING_ID NUMBER,
    DESTINATION_TYPE VARCHAR,
    CUSTOMER_ID NUMBER,
    AMOUNT_SPENT NUMBER,
    COUNTRY_CODE VARCHAR,
    ADDRESS VARCHAR,
    EMAIL VARCHAR,
    LAST_NAME VARCHAR,
    BOOKING_TIME VARCHAR
);


CREATE OR REPLACE TABLE CUSTOMER_BOOKINGS_STAGING LIKE CUSTOMER_BOOKINGS_DATA;
